#!/bin/bash

# install z3
mkdir thirdparty
pushd thirdparty
wget https://github.com/Z3Prover/z3/archive/refs/tags/z3-4.13.0.tar.gz
tar xvfz z3-4.13.0.tar.gz
pushd z3-z3-4.13.0
python3 scripts/mk_make.py
pushd build
make -j 8
popd
z3path=`pwd`
echo ${z3path}
popd
popd
sz3path=${z3path//\//\\\/}
sed -i "s/Z3PATH/${sz3path}/g" src/CMakeLists.txt

# install gurobi
pushd thirdparty
wget https://packages.gurobi.com/9.1/gurobi9.1.2_linux64.tar.gz
tar xvfz gurobi9.1.2_linux64.tar.gz
pushd gurobi912/linux64
gurobipath=`pwd`
sgurobipath=${gurobipath//\//\\\/}
popd
popd
sed -i "s/GUROBIPATH/${sgurobipath}/g" src/CMakeLists.txt
# select the static library of gurobi
gcc_major_version=`echo __GNUC__ | gcc -E -xc - | tail -n 1`
gcc_minor_version=`echo __GNUC_MINOR__ | gcc -E -xc - | tail -n 1`
gcc_version=$gcc_major_version.$gcc_minor_version
if [ $gcc_version = 4.6 ] || [ $gcc_version = 4.8 ]
then
    sed -i "s/5.2.a/4.2.a/g" src/CMakeLists.txt
fi


# make surface language
path=`pwd`
spath=${path//\//\\\/}
sed -i "s/SUFUPATH/\"${spath}\"/g" exp/python/config.py
pushd src/surface
make
popd

# install AutoLifter
pushd thirdparty
git clone https://github.com/jiry17/AutoLifter.git
pushd AutoLifter 
./install 
popd 
popd


# get Synduce
# mkdir baseline
# pushd baseline
# git clone https://github.com/synduce/Synduce.git
# pushd Synduce
# ./setup.sh
# popd
# popd

# get Grisette
echo 'export PATH="$HOME/.cabal/bin:$PATH"' >> ~/.bashrc
source ~/.bashrc
cabal install grisette

# build source
pushd src
path=`pwd`
spath=${path//\//\\\/}
sed -i "s/SOURCEPATH/\"${spath}\"/g" basic/config.cpp
popd

mkdir build
pushd build
cmake -G Ninja ../src
ninja
popd

